apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helse-brreg
  namespace: risk
  labels:
    team: risk
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{ image }}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  resources:
    limits:
      memory: {{memory_lim}}
    requests:
      cpu: {{cpu_req}}
      memory: {{memory_req}}
  accessPolicy:
    outbound:
      external:
       - host: data.brreg.no
    inbound:
      rules:
        - application: orginfo
        - application: orginfo-open
  env:
    - name: JDK_JAVA_OPTIONS
      value: "-Xmx1536m"
  prometheus:
    enabled: true
    path: /metrics
