apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helse-brreg
  namespace: risk
  labels:
    team: risk
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 3
  liveness:
    path: /isalive
  readiness:
    path: /isready
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  accessPolicy:
    outbound:
      external:
       - host: data.brreg.no
    inbound:
      rules:
        - application: orginfo
        - application: orginfo-open
  env:
    - name: JDK_JAVA_OPTIONS
      value: "-Xmx1536m"
  prometheus:
    enabled: true
    path: /metrics
